import type { AutonomyProjectState } from "./autonomyDomain";

export function projectAutonomyState(projectId: string, project: AutonomyProjectState | undefined) {
  if (!project) return {
    available: false,
    projectId,
    gaps: [],
    missions: [],
    decisions: [],
    coverageSnapshots: [],
    surfaces: [],
    specialists: [],
  };

  return {
    available: true,
    projectId,
    intentVersion: project.intentVersion,
    updatedAt: project.updatedAt,
    lastDiscoveryAt: project.lastDiscoveryAt,
    surfaces: (project.surfaces ?? []).map((surface) => ({
      id: surface.id,
      key: surface.key,
      name: surface.name,
      description: surface.description,
      parentKey: surface.parentKey,
      origin: surface.origin,
      status: surface.status,
      risk: surface.risk,
      sourceRefs: [...surface.sourceRefs],
      createdAt: surface.createdAt,
      updatedAt: surface.updatedAt,
      lastExploredAt: surface.lastExploredAt,
    })),
    specialists: (project.specialists ?? []).map((specialist) => ({
      id: specialist.id,
      key: specialist.key,
      name: specialist.name,
      focus: specialist.focus,
      rationale: specialist.rationale,
      surfaceRefs: [...specialist.surfaceRefs],
      origin: specialist.origin,
      status: specialist.status,
      createdAt: specialist.createdAt,
      updatedAt: specialist.updatedAt,
      lastRunAt: specialist.lastRunAt,
    })),
    gaps: project.gaps.map((gap) => ({
      id: gap.id,
      category: gap.category,
      title: gap.title,
      summary: gap.summary,
      status: gap.status,
      source: gap.source,
      priority: gap.priority,
      impact: gap.impact,
      uncertainty: gap.uncertainty,
      novelty: gap.novelty,
      urgency: gap.urgency,
      evidenceNeeded: [...(gap.evidenceNeeded ?? [])],
      sourceRefs: [...(gap.sourceRefs ?? [])],
      createdAt: gap.createdAt,
      updatedAt: gap.updatedAt,
      resolvedAt: gap.resolvedAt,
    })),
    missions: project.missions.map((mission) => ({
      id: mission.id,
      gapId: mission.gapId,
      role: mission.role,
      objective: mission.objective,
      evidenceContract: [...mission.evidenceContract],
      status: mission.status,
      priority: mission.priority,
      attempt: mission.attempt,
      startCycle: mission.startCycle,
      createdAt: mission.createdAt,
      updatedAt: mission.updatedAt,
      startedAt: mission.startedAt,
      completedAt: mission.completedAt,
      lastDecisionId: mission.lastDecisionId,
    })),
    decisions: project.decisions.map((decision) => ({
      id: decision.id,
      purpose: decision.purpose,
      provider: decision.provider,
      model: decision.model,
      confidence: decision.confidence,
      latencyMs: decision.latencyMs,
      createdAt: decision.createdAt,
    })),
    coverageSnapshots: project.coverageSnapshots.map((snapshot) => ({
      id: snapshot.id,
      open: snapshot.open,
      unexplored: snapshot.unexplored,
      investigating: snapshot.investigating,
      blocked: snapshot.blocked,
      resolved: snapshot.resolved,
      highPriorityOpen: snapshot.highPriorityOpen,
      risk: snapshot.risk,
      convergence: snapshot.convergence,
      createdAt: snapshot.createdAt,
    })),
  };
}
